### ISSUE TITLE
Managing macOS Certificates/Provisioning Profiles

### ISSUE THREAD

**Issue by vastopa** [zeplin/fastlane-plugin-notarize#11]
Hey! Sorry for the somewhat unrelated question to your plugin.. I'm wondering how a user of this plugin should be managing their Developer ID macOS certificate in a CI workflow when using this plugin. 

Currently fastlane match does not support managing any type of macOS certificate/profile, let alone the specific one for notarization. 

Any suggestions or tips on how to do this would be greatly appreciated!

**Comment by lazerwalker** [comment]
Just wanted to add a +1 to this. @vastopa, let me know if you figure things out!

Looks like Spaceship supports Mac provisioning profiles, so I'm currently investigating what it'd take to add macOS profile support to fastlane match, but would love an easier solution :)

**Comment by berkcebi** [comment]
I just checked our workflow. Since we're using Bitrise as our CI, they have a step to install a certificate, looks like we're running that step before we run fastlane.

**Comment by yigitcanyurtsever** [comment]
Hey @vastopa and @lazerwalker 👋 

Just wanted to let you know fastlane now officially supports macOS with the latest release. You may want to check it out. 🙌

**Comment by vastopa** [comment]
I saw that - exciting stuff! Will close this issue then 😁

**Comment by lazerwalker** [comment]
FWIW, while Fastlane now officially supports macOS, my understanding is that proper support for the Developer ID certificate (which is necessary to notarize apps not being distributed via the MAS) isn't coming until a future release. I'm not sure this specific use case is actually solved yet.
