### ISSUE TITLE
suggestion - turn on the log for notarisation file upload

### ISSUE THREAD

**Issue by ConfusedVorlon** [zeplin/fastlane-plugin-notarize#9]
I hit a bunch of issues related to my account password and multiple teams

they were pretty easy to identify once I went into the source and manually recreated the notarization_upload_command (apple error messages were for unusually helpful)

at the moment, the plugin just gives unhelpful errors like 'script exited with code 160'

how about just turning on the log

```
        notarization_upload_response = Actions.sh(
          notarization_upload_command,
          log: true
        )
```

or alternatively allowing that with an optional 'verbose' param

**Comment by berkcebi** [comment]
Adding a verbose option makes a lot of sense!
